### ISSUE TITLE
no password

### ISSUE THREAD

**Issue by terminal-9** [suzandavis/Lost-wallet-finder#1]
pls what is the password to the zip

**Comment by ESI804** [comment]
> pls what is the password to the zip

**Comment by Angel-with-shotgun** [comment]
Did find the password

**Comment by BunnySAngel** [comment]
PASSWORD PLS

**Comment by BunnySAngel** [comment]
> Did find the password

Did you get password

**Comment by ebrahim2163** [comment]
Password?

**Comment by Vera728** [comment]
Where can I get the password

**Comment by Jaydip004** [comment]
Please tell the password

**Comment by iphone700** [comment]
email pwd to iphonecoin007@gmail.com

**Comment by suzandavis** [comment]
repo is updated
